[tool.poetry]
name = "lab2-assign"
version = "0.1.0"
description = ""
authors = ["Oyeon <data0311@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ultralytics = "^8.3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
